apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: samba
  name: samba
  namespace: default
spec:
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - image: docker.io/dperson/samba:latest
          args:
            - "-u"
            - "roc;111111"
            - "-s"
            - "data;/data/;yes;no;yes;all;all;all"
            - "-w"
            - "WORKGROUP"
            - "-g"
            - "force user=roc"
            - "-g"
            - "guest account=roc"
            - "-S"
          imagePullPolicy: IfNotPresent
          name: samba
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data
              name: data
      dnsPolicy: Default
      hostNetwork: true
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /data
            type: DirectoryOrCreate
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
